
### Create Patients
GET localhost:8080/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlcmljYmFuZTAzQGdtYWlsLmNvbSIsImlhdCI6MTczMTY5MTUwMywiZXhwIjoxNzMxNzI3NTAzfQ.x5_dy29gR5pv4GFy9QQ0O0xVxXmYGplNw9Ssafna-nQ

### Create Patient Hardcoded
POST localhost:8080/createPatient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlcmljYmFuZTAzQGdtYWlsLmNvbSIsImlhdCI6MTczMTY5MTUwMywiZXhwIjoxNzMxNzI3NTAzfQ.x5_dy29gR5pv4GFy9QQ0O0xVxXmYGplNw9Ssafna-nQ

{
  "id": 1,
  "firstName": "Joh",
  "lastName": "Doe",
  "gender": "MALE",
  "personalNumber": "12349856-7890",
  "phone": "1234586849",
  "birthDate": "2024-01-01",
  "address": "123 Main St",
  "maritalStatus": "SINGLE"
}

### Get Practitioners
GET localhost:8080/practitioners

### Create Practitioner Hardcoded
GET localhost:8080/create-practitioner


### Login User
POST localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "ericbane03@gmail.com",
  "password": "doctor"
}


### Create User
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "ericbane03@gmail.com",
  "password": "doctor",
  "firstName": "Eric",
  "lastName": "Bane",
  "role": "DOCTOR"
}
